Recursive assembly resolver (required for #127)
Pryaxis/TSAPI pull request #128
Opened 2017-04-20 20:51 UTC by deadsurgeon42

This searchs for any folder inside `ServerPlugins/` so assemblies can be resolved correctly.

2017-04-20 20:56 UTC, ProfessorXZ commented
Just to elaborate a bit on this; the previous PR ([#127](https://github.com/NyxStudios/TerrariaAPI-Server/pull/127)) worked fine if you created a new folder inside serverplugins and put the plugin there, but due to the nature of TSAPI's AssemblyResolve handler it failed to load the plugin that had other dependencies because it was looking for them in the wrong place.

2017-04-20 21:14 UTC, deadsurgeon42 commented
Please don't merge as I need to edit this to use full assembly name and not just dll

2017-04-21 15:15 UTC, hakusaro approved these changes
The faster this gets merged, the better.

2017-04-22 09:14 UTC, deadsurgeon42 commented
There are bigger issyes like some assemblies like json.net are strong named so they expect the exact version and I'll remake the pr for the new branch so don't merge pls.

2017-04-22 17:32 UTC, deadsurgeon42 commented
This gotta fix at least finding json.net.

2017-04-22 22:01 UTC, hakusaro commented
cc @NyxStudios/tshock

2017-04-26 09:45 UTC, WhiteXZ commented
@deadsurgeon42 what level of testing has this had?
Could you list all the intended features and whether or not it accomplishes them (via a github checklist)

2017-04-26 14:13 UTC, deadsurgeon42 commented
Currently using it with 25+ plugins in Aurora and nothing's going wrong yet.
- [x] Allows nicely categorizing plugins (even tshock) in their subdirectories.
- [x] Can directly `git clone` most repositories right into ServerPlugins/ (with only one plugin dll in their repos) and run them. This could be an interesting way to code a plugin autoinstaller/updater? (with https://github.com/libgit2/libgit2sharp or similar)
- [ ] One possible issue with the above is some repos have multiple copies/forms of the plugin (bin/Debug|Release or obj/ and /bin) so they crash the server.
- [ ] An addition to above feature could be making sure only one of a plugin is loaded at a time (check dll name or full name?) so plugins can even be developed and built right from ServerPlugins/ without need for weird debug/run configuration.

- [ ] can't seperate dependency assembly versions because that needs resolving their full name (I could try to expand the functionality for that if you want), it just uses whatever it find first

2017-04-27 00:24 UTC, tylerjwatson commented
So what happens in this scenario:

```
Given I have a plugin structure of the following:
ServerPlugins/a/Newtonsoft.Json.dll,Version=9.0.1.0,PublicKeyToken=null
ServerPlugins/a/b/c/Newtonsoft.Json.dll,Version=10.0.0.2,PublicKeyToken=null
And I ask to resolve Newtonsoft.Json,Version=10.0.0.2,PublicKeyToken=null
Then the assembly I get should load from ServerPlugins/a/b/c.
```

2017-04-27 07:02 UTC, deadsurgeon42 commented
It loads from /a/ as it is now, possibly crashing up.

2017-04-28 11:16 UTC, deadsurgeon42 commented
@tylerjwatson now it works almost exactly as you described but with one difference:
If two assemblies with the exact same full name exist, whatever's found first is loaded which is fine for everything but the most edge cases (modified unsigned assembly with unedited full name).

2017-04-28 12:06 UTC, AxisKriel approved these changes
LGTM
Feel free to merge at will once you're satisfied with the results @tylerjwatson

2017-04-28 15:12 UTC, hakusaro requested changes
This code was tested and working on macOS Sierra. To test, I downloaded the latest dev artifacts from AV, then made a "ServerPlugins/PRISM/DArkly/すし" directory and put TShockAPI.dll inside. Then, in the directory above it, I threw some random DLLs that TShock needed. Server loaded correctly.

```
Kurisu 福 ~/Downloads/MintakaDebug (1)
7643 ◯ : ls ServerPlugins/PRISM/DArkly/すし                                  ⏎
TShockAPI.dll

Kurisu 福 ~/Downloads/MintakaDebug (1)
7644 ◯ : ls ServerPlugins/PRISM/DArkly/
BCrypt.Net.dll       Mono.Data.Sqlite.dll すし
HttpServer.dll       MySql.Data.dll
```

2017-04-28 15:12 UTC, hakusaro commented on TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
> +			foreach (var path in paths)
I'm not a syntax nut but we should really get some braces in here. This Python style indentation based code hurts my head.

2017-04-28 15:18 UTC, Ijwu commented on TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
> +			foreach (var path in paths)
I'd also prefer all `foreach` constructs use braces no matter the statements under them. I'd be ok with getting away with single-line `if`s but a `foreach` is too complex.

2017-04-28 15:18 UTC, deadsurgeon42 commented on TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
> +			foreach (var path in paths)
Oh sorry I had added braces in my local repo but forgot to save before pushing whoops.

2017-04-28 15:25 UTC, hakusaro approved these changes
Brace for impact, because this...

![lgtm_6](https://cloud.githubusercontent.com/assets/532647/25535519/987f1f1a-2bf4-11e7-80e2-0c1f5e09d289.gif)

2017-04-28 15:29 UTC, deadsurgeon42 commented
Tested again with 36 plugin repos cloned into ServerPlugins/ ( not all were 2.1) and they all run good.
```
[Server API] Info Plugin ChangeName v1.3.4.1 (by Zaicon) initiated.
[Server API] Info Plugin EmergencyRoom v1.0.3.22 (by Granpa-G) initiated.
[Server API] Info Plugin History v1.6.1.1 (by Maintained by Cracker64 & Zaicon) initiated.
[Server API] Info Plugin MoreAdminCommands v1.1.3.1 (by Zaicon) initiated.
[Server API] Info Plugin AntiWOF-2 v1.1.1.0 (by Simon311) initiated.
TShock 4.3.23.0 (Mintaka) now running.
AutoSave Enabled
Backups Disabled
Welcome to TShock for Terraria. Initialization complete.
[Server API] Info Plugin TShock v4.3.23.0 (by The TShock Team) initiated.
[Server API] Info Plugin Clans3 v1.3.1.1 (by Zaicon) initiated.
[Server API] Info Plugin DieMob Regions v1.0.1.0 (by Zaicon) initiated.
[Server API] Info Plugin Emotes v1.0 (by White) initiated.
[Server API] Info Plugin GDRegions v1.0.1.1 (by Zaicon) initiated.
[Server API] Info Plugin InfiniteChests v1.0.8.0 (by Zaicon) initiated.
[Server API] Info Plugin InfiniteSigns v1.4.5.1 (by Maintained by Zaicon) initiated.
[Server API] Info Plugin LastOnline v1.1.1.0 (by Ancientgods, Enerdy) initiated.
[Server API] Info Plugin Region Vision v1.2.9.0 (by Andrio Celos) initiated.
[Server API] Info Plugin SummonLimit v1.4.0.0 (by Newy) initiated.
[Server API] Info Plugin TSReward v1.2.0.0 (by Ancientgods & Enerdy) initiated.
[Server API] Info Plugin User Specific Functions v1.4.8.0 (by Professor X) initiated.
[Server API] Info Plugin Warpplate v2.0.0.0 (by Maintained by Zaicon) initiated.
[Server API] Info Plugin WhoExtras v1.0.0.0 (by Newy) initiated.
[Server API] Info Plugin WorldEdit v1.5.0.0 (by Nyx Studios) initiated.
[Server API] Info Plugin Essentials v3.0.5.1 (by Zaicon) initiated.
[Server API] Info Plugin HousingDistricts v2.4.0.0 (by Twitchy, Dingo, radishes, CoderCow and Simon311) initiated.
[Server API] Info Plugin BuildMode v1.1.1.3 (by MarioE) initiated.
[Server API] Info Plugin IceWand v1.1.5.1 (by Zaicon) initiated.
[Server API] Info Plugin Name Validator v1.2.3.0 (by Enerdy) initiated.
[Server API] Info Plugin AntiSpam v1.2.0.0 (by Zaicon) initiated.
```

2017-04-29 03:15 UTC, tylerjwatson commented
@deadsurgeon42 cool, so we are only worried about FullName as in the case of versions.  Dependencies of dependencies can be a nightmare, since most stuff is moving to NuGet components.  If you can confirm that it will recursively look for a specific version of an assembly and not just stop at the first assembly it finds of that name, then all good for merge.

2017-04-29 11:32 UTC, deadsurgeon42 commented
@tylerjwatson I'm testing this with two test plugins. They only search youtube for the given string during `Initialize()`. I created the solution folders directly inside serverplugins.
The plugins both reference https://www.nuget.org/packages/Google.Apis.YouTube.v3/ from nuget which is a fairly complex package with native dependencies, but with a difference: The new one references latest version `1.25.0.760` while the old one references `1.22.0.760`.
![image](https://cloud.githubusercontent.com/assets/5434547/25555201/8413309e-2ce8-11e7-8b23-4e32896c34a4.png)
Sadly it didn't work as the new assembly is used in both but they both function.
`typeof(YouTubeService).Assembly.FullName` is the way I got the type.

2017-04-29 19:45 UTC, deadsurgeon42 commented
I'm researching why only one version of an assembly is used and maybe it's because everything is loaded into the same AppDomain?
https://dzone.com/articles/dll-heaven-multiple-versions-o
>Because when an assembly is loaded it cannot be unloaded so if we have 2 different assemblies once a type has been loaded from one of them, it will be reused each time we want to instantiate a type.

2017-04-30 02:09 UTC, tylerjwatson approved these changes

2017-04-30 14:56 UTC, merged